### ISSUE TITLE
How is SickleUI obsolete?

### ISSUE THREAD

**Issue by newclarityex** [UmbraLuminosa/sickle_ui#1]
Hello! I've been reexploring UI dev options in bevy recently, and I stumbled upon this crate that appears to largely simplify and improve the UI experience as well as adding useful widgets. I noticed that it was marked as unnecessary with 0.15, but I don't see any new widgets for 0.15, and didn't see any improvements in the RC and milestone issues either.

**Comment by eidloi** [comment]
@newclarityex The issue is that the low level UI API in Bevy lost a critical guarantee in 0.15 with the addition of the GhostNodes.

These are non-ui elements that _could_ be injected into the hierarchy for reactive-style control purposes to proxy their children to take their place in the layout and rendering step. Of course you don't _have_ to use them, but BSN (the new scene format) is expected to rely on them and it could happen that Bevy adds mid-level widgets that rely on it. For example the new cosmic text integration _almost_ used them. 

Since ghost nodes are resolved during layout they have no size, their children (and this is recursive) cannot be enumerated without dedicated helpers that are a _different_ API than the existing one. Ignoring them during manipulation of the tree is undefined behavior (because their children are _supposed_ to be siblings of themselves). **This additional _meta_ dimension means that the widget tree is no longer guaranteed to be _the_ exact configuration tree of the UI, locking out external authors from creating a mid-level API over bevy_ui.** At least ones that wish to use the widget tree as the single source of truth and only use it via the ECS.

You can't just take a UI element and _move_ it somewhere else, especially not shuffle one among its siblings. What if the node next to it is part of a GhostNode? Or is inside a GhostNode in another GhostNode? Who is controlling the content of that node and when is it scheduled for an update? If I move it would it be re-created or deleted?

True, the GhostNodes have been moved to "experimental" due to my heavy push-back, but it is strongly implied they will remain.
However I'll not wait 6 months for this to settle, nor will I - **in good faith** - suggest to anybody to adapt and put work into building on sickle_ui, knowing full well it could blow up for reasons outside of both mine and the users control. I also won't attempt to work around this issue, sickle_ui relies heavily on traversing and manipulating the widget tree, again, as the single source of truth. Ignoring / supporting ghost nodes is simply not feasible (or _supportable_). It is like trying to use jQuery with a React shadow DOM: possible, but _why_ would you?

The crate also lost its purpose in offering a mid and high level API for the editor UI since the Bevy editor will be based entirely on BSN and the working group simply ignored (and _has_ to ignore) it.

That said `sickle_ui` will live but it will no longer use neither bevy_ui nor bevy_text, thus losing any remaining open source relevance. (And I don't really see a point in sharing the UI/Text layout and rendering crate that I am building for it, who in their right mind would use _that_?).

P.S: I also think GhostNodes have no business existing, they pollute a perfectly good hierarchy and halve the performance of the entire UI stack. They are a cheap solution for a superficial problem and lock out the original approach to 1-1 manage the low level UI (a direct result of a decision making process that has no appointed SME, just loud people). The fact that they are pushing to add them _everywhere_ (not just UI!) makes me straight up _furious_ as an architect and _user_ of Bevy, but it's their choice so 🤷.

**Comment by newclarityex** [comment]
Thank you for the response. This seems very unfortunate, and it feels like a backwards step for UI in bevy. I love using reactivity in UI development, but GhostNodes seem like a solution that should be an abstraction on top of the existing API, rather than pushed to be integrated into everything. I understand your frustration, and it really feels like a shame to have lost this part of the ecosystem. It doesn't feel like sickle_ui has been made obsolete, but rather that it's been left in the dust with no replacement.
