### ISSUE TITLE
Add trait for UiBuilder

### ISSUE THREAD

**Issue by UkoeHB** [UmbraLuminosa/sickle_ui#14]
I recommend moving the `spawn` method from`UiBuilder` to a trait implemented by both `UiRoot` and `Entity` variants. Then you only need a single impl for extension traits, using the `T: UiSpawner` trait bound.

**Comment by eidloi** [comment]
This makes sense

**Comment by eidloi** [comment]
> On second thought this makes less sense to me. `spawn` for the `UiRoot` version means 'create self', while `spawn for `Entity` version means 'create child'.

The reason I had the double implementation is because there aren't many elements that support being a Root element. Basically rows and columns. The current version would let us create a widget with a different setup if they are root elements. Not sure how useful it is, but let's keep it as it is now and revisit later when there are more use-cases

**Comment by eidloi** [comment]
Another, albeit crude example would be that a root-spawn could insert the default theme automatically. Or we could have an extension only on the UiRoot that does that (i.e. `ui_builder.themed_root(...)`

**Comment by eidloi** [comment]
Let's keep it as-is. If we run into an issue where it becomes too much to maintain the two, we can revisit then. Cheers.
