### ISSUE TITLE
No way to justify text ? 

### ISSUE THREAD

**Issue by ethereumdegen** [UmbraLuminosa/sickle_ui#68]
I found no style() command to justify text with  JustifyText  so i just built one myself.  

btw it would be really nice to have a list of all of the style() commands like .margin and so forth because my code editor cant autocomplete unimported extensions.  !

**Comment by eidloi** [comment]
Justify text never worked for me the way I expected in Bevy, so I forgot to add it. That said, I am working on a text solution, so I'll not add this specifically for the moment.

As for the style: There is a prelude you can import which will expose all extensions, which is the preferred way of using it. You can either use the whole `sickle_ui::prelude::*` or just take the `sickle_ui::sickle_ui_scaffold::prelude::*` or even directly `sickle_ui::sickle_ui_scaffold::ui_style::prelude::*`. Since `sickle_ui_scaffold` has its own crate, you can depend on it directly and shorten the import.

Documentation: Yeah, it's an effort I have to find time for.
