### ISSUE TITLE
Cant figure out how to make a scrollbox 

### ISSUE THREAD

**Issue by ethereumdegen** [UmbraLuminosa/sickle_ui#82]
Is there some special trick to making a scrollbox?  How does it work ? Doesnt seem super idiomatic.  

Tried this and no beans 

```
      commands 
          .ui_builder(right_container_node)
            .container(NodeBundle{


             style: Style {
                border: UiRect::all(Val::Px(2.0)),
                ..default()
            },
             border_color: LinearRgba::rgb(0.9, 0.9, 0.9).into(),
             background_color: LinearRgba::new(0.185,0.51,0.8,0.58).into() , 


            ..default()


        }, |inner| {


         inner.scroll_view(
            Some( ScrollAxis::Vertical), |scroll_view| { 
             
 

               scroll_view
               .column(|column| {

                    column.vertical_choice_menu(VerticalChoiceMenuConfig {
                            choices: Vec::new() , //change this to be all the campaigns !! 

                            ..default()
                        })
                    .insert( SaveFileVerticalMenuRoot )
                    .id();
                   // column.entity_commands().add_child(  vertical_choice_menu )  ;
               })
                ;
               


        } )
          .style()
          .min_height( Val::Px(300.0) )
          .min_width( Val::Px(400.0)  ) ;

        }); //container
```

**Comment by eidloi** [comment]
it works for me! Maybe the confusion is that the scroll bar won't appear until the available height is filled? I added this four times instead of the `vertical_choice_menu`:

```rust
column
  .row(|_| {})
  .style()
  .height(Val::Px(100.))
  .background_color(
      LinearRgba::rgb(
          0.9, 0.8, 0.7,
      )
      .into(),
  );
```
![Screenshot_197](https://github.com/user-attachments/assets/21063628-c821-4162-8c60-280f6d8b4094)

**Comment by eidloi** [comment]
@ethereumdegen did it work out in the end?

**Comment by Fincap** [comment]
I'm uncertain if this issue I'm having is related, but I have a feeling it likely has the same root cause.

```rust
...

column
  .scroll_view(Some(ScrollAxis::Vertical), |scroll_view| {
      scroll_view.button("Button");
      scroll_view.button("Button");
      scroll_view.button("Button");
      scroll_view.button("Button");
  })
  .style()
  .min_height(Val::Px(100.))
  .background_color(Color::hex("#383A40").unwrap());

...
```

results in a gap of the correct height where the scroll bar should be:

![img1](https://github.com/user-attachments/assets/5acbd153-bcec-4fb8-b09b-6df8c357dad2)

Modifying the style parameters to include:
 ```rust
.min_width(Val::Px(100.))
```

displays the scroll view with the correct width:

![img2](https://github.com/user-attachments/assets/1d8ab2c3-0259-427f-b601-4d88b63995fe)

However, setting 
 ```rust
.width(Val::Auto)
```

instead results in the same output as the first screenshot, with the scroll view is invisible.

Inspecting the `Style` component of the node containing the `ScrollView` component using `bevy-inspector-egui` shows that this parameter is being overwritten somewhere and reverting back to `Val::Percent(100.)`.

![img3](https://github.com/user-attachments/assets/2b204ecc-3688-4f47-8e91-9459e923c382)

Manually changing the width to `Val::Auto` here in the inspector instantly reverts the value back to `Val::Percent(100.)`, however interestingly the scroll bar will now appear:

![img4](https://github.com/user-attachments/assets/fcd758b0-1147-459e-b298-91f069e864b9)

Changing the width to `Val::Auto` for a second time will preserve the change, and will correctly display the scroll view as you would expect it to with width set to auto:

![img5](https://github.com/user-attachments/assets/8184ce45-5e22-4a92-86af-05c3c451f442)

My workaround solution to this has been to wrap the scroll view in a panel, and apply the size styles to the wrapping panel rather than the scroll view itself.
